-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 14, 2022 at 06:21 AM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `e-exam`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `id` int(11) NOT NULL,
  `name` varchar(225) DEFAULT NULL,
  `contact` varchar(10) DEFAULT NULL,
  `email` varchar(200) NOT NULL,
  `password` int(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id`, `name`, `contact`, `email`, `password`) VALUES
(1, 'JUHI SINGH', '7489134761', 'juhi@gmail.com', 1234);

-- --------------------------------------------------------

--
-- Table structure for table `exam_schedule`
--

CREATE TABLE `exam_schedule` (
  `id` int(11) NOT NULL,
  `branch` varchar(100) DEFAULT NULL,
  `semester` int(1) NOT NULL,
  `subject` varchar(100) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `time_start` time DEFAULT NULL,
  `time_end` time DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `exam_schedule`
--

INSERT INTO `exam_schedule` (`id`, `branch`, `semester`, `subject`, `date`, `time_start`, `time_end`) VALUES
(7, 'CSE', 5, 'CYBER SECURITY', '2022-04-11', '10:05:00', '22:10:00');

-- --------------------------------------------------------

--
-- Table structure for table `mcq`
--

CREATE TABLE `mcq` (
  `id` int(11) NOT NULL,
  `branch` varchar(50) DEFAULT 'CSE',
  `semester` int(1) DEFAULT 5,
  `subject` varchar(50) DEFAULT 'INTERNET AND WEB TECHNOLOGY',
  `question` varchar(1000) DEFAULT NULL,
  `a` varchar(500) DEFAULT NULL,
  `b` varchar(500) DEFAULT NULL,
  `c` varchar(500) DEFAULT NULL,
  `d` varchar(500) DEFAULT NULL,
  `answer` varchar(500) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `mcq`
--

INSERT INTO `mcq` (`id`, `branch`, `semester`, `subject`, `question`, `a`, `b`, `c`, `d`, `answer`) VALUES
(1, 'CSE', 5, 'TOC', 'L = (an bn an | n = 1,2,3)  is an example of a language that is', 'Context free', 'Not context free', 'Not context free but whose complement is CF', 'Both (b) and (c)', 'Both (b) and (c)'),
(2, 'CSE', 5, 'TOC', 'The set of all strings over the alphabet S = {a, b} (including e) is denoted by', '(A) (a + b)*', '(a + b)+', 'a+b+', 'a*b*', '(A) (a + b)*'),
(3, 'CSE', 5, 'TOC', 'Which of the following strings is not generated by the following grammar? S ? SaSbS|e', 'aabb', 'abab', 'aababb', 'aaabb', 'aaabb'),
(4, 'CSE', 5, 'TOC', 'Which of the following regular expression identity is true?', 'r(*) = r*', '(r*s*)* = (r + s)*', '(r + s)* = r* + s*', 'r*s* = r* + s*', '(r*s*)* = (r + s)*'),
(5, 'CSE', 5, 'TOC', 'The logic of pumping lemma is a good example of', 'Pigeon-hole principle', 'Divide-and-conquer technique', 'Recursion', 'Iteration', 'Pigeon-hole principle'),
(6, 'CSE', 5, 'TOC', 'Context-free grammar can be recognized by', 'Finite state automation', '2-way linear bounded automata', 'Push down automata ', 'Both (b) and (c)', 'Both (b) and (c)'),
(7, 'CSE', 5, 'TOC', 'Which of the following does not belong to the language if input alphabet set is', 'a', 'b', 'epsilon', 'c', 'epsilon'),
(8, 'CSE', 5, 'TOC', 'TOC stands for :', 'Theory Of Computer ', 'Theory Of Calculator', 'Theory Of Computation', 'Theory Of Calcus', 'Theory Of Computation'),
(9, 'CSE', 5, 'TOC', 'Which of the following CFG\'s can\'t be simulated by an FSM?', 'S --> Sa | b', 'S  --> aSb | ab', 'S --> abX,  X --> cY,  Y --> d | aX', 'None of these', 'S  --> aSb | ab'),
(10, 'CSE', 5, 'TOC', 'Set of regular languages over a given alphabet set is closed under', 'Union', 'Complementation', 'Intersection', 'All of these', 'All of these'),
(11, 'CSE', 5, 'DBMS', 'A collection of interrelated records is called a', 'Database', 'Spreadsheet', 'Management information system', 'Text file', 'Database'),
(12, 'CSE', 5, 'DBMS', 'The method of file organization in which data records in a file are arranged in a specified order according to key field is known as the', 'Sequential access method', 'Queuing method', 'Predetermined method', 'Direct access method', 'Sequential access method'),
(13, 'CSE', 5, 'DBMS', 'Unlike filters queries can be saved as in a database.', 'Database', 'Filters', 'Objects', 'Any of the above', 'Objects'),
(14, 'CSE', 5, 'DBMS', 'ROLLBACK in a database is ____ statement.', 'DDL', 'DML', 'DCL', 'TCL', 'TCL'),
(15, 'CSE', 5, 'DBMS', 'External database is', 'Database created using DBMS package', 'Database created in MS-Word', 'Database created in EXCEL', 'All of the above', 'Database created using DBMS package'),
(16, 'CSE', 5, 'DBMS', 'Report generators are used to', 'Store data input by a user', 'Retrieve information from files', 'Answer queries', 'Both (b) and (c)', 'Both (b) and (c)'),
(17, 'CSE', 5, 'DBMS', 'The logical data structure with a one-to-many relationship is a', 'Tree', 'Chain', 'Network', 'All of these', 'Tree'),
(18, 'CSE', 5, 'DBMS', 'In a database, related fields are grouped to', 'File', 'Bank', 'Menu', 'Data record', 'Data record'),
(19, 'CSE', 5, 'DBMS', 'The database environment has all the following components except', 'Database administrator', 'Database', 'Users', 'Separate files', 'Separate files'),
(20, 'CSE', 5, 'DBMS', 'Which database handles full text data, image, audio and video?', 'Multimedia database', 'Video on demand database', 'Graphics database', 'Transaction database', 'Multimedia database'),
(21, 'CSE', 5, 'CYBER SECURITY', 'In which of the following, a person is constantly followed/chased by another person or group of several peoples?', 'Phishing', 'Bulling', 'Stalking', 'Identity theft', 'Stalking'),
(22, 'CSE', 5, 'CYBER SECURITY', 'Which one of the following can be considered as the class of computer threats?', 'Dos Attack', 'Phishing', 'Soliciting', 'Both A and C', 'Dos Attack'),
(23, 'CSE', 5, 'CYBER SECURITY', 'Which of the following is considered as the unsolicited commercial email?', 'Virus', 'Malware', 'Spam', 'All of the above', 'Spam'),
(24, 'CSE', 5, 'CYBER SECURITY', 'Which of the following usually observe each activity on the internet of the victim, gather all information in the background, and send it to someone else?', 'Malware', 'Spyware', 'Adware', 'All of the above', 'Spyware'),
(25, 'CSE', 5, 'CYBER SECURITY', '_______ is a type of software designed to help the user\'s computer detect viruses and avoid them.', 'Malware', 'Adware', 'Antivirus', 'Both B and C', 'Antivirus'),
(26, 'CSE', 5, 'CYBER SECURITY', 'Which one of the following is a type of antivirus program?', 'Quick heal', 'Mcafee', 'Kaspersky', 'All of the above', 'All of the above'),
(27, 'CSE', 5, 'CYBER SECURITY', ' It can be a software program or a hardware device that filters all data packets coming through the internet, a network, etc. it is known as the_______:', 'Antivirus', 'Firewall', 'Cookies', 'Malware', 'Firewall'),
(28, 'CSE', 5, 'CYBER SECURITY', 'Which of the following refers to stealing one\'s idea or invention of others and use it for their own benefits?', 'Piracy', 'Plagiarism', 'Intellectual property rights', 'All of the above', 'Plagiarism'),
(29, 'CSE', 5, 'CYBER SECURITY', 'Which of the following refers to exploring the appropriate, ethical behaviors related to the online environment and digital media platform?', 'Cyber low', 'Cyberethics', 'Cybersecurity', 'Cybersafety', 'Cyberethics'),
(30, 'CSE', 5, 'CYBER SECURITY', 'Which of the following refers to the violation of the principle if a computer is no more accessible?', 'Access control', 'Confidentiality', 'Availability', 'All of the above', 'Availability'),
(31, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'From which tag the descriptive list starts?', '<LL>', '<DD>', '<DL>', '<DS>', '<DL>'),
(32, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'The elements and have the following characteristics', 'Element inherits properties defined for in a stylesheet', 'And have no real meanings as html tags unless stylesheet is applied', 'Elements and define content to be inline or block-level', 'And are used as alternatives for the element', 'Elements and define content to be inline or block-level'),
(33, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'The latest HTML standard is', 'XML', 'SGML', 'HTML 4.0', 'HTML 5.0', 'HTML 5.0'),
(34, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'While working on a JavaScript project, in your JavaScript application, which function would you use to send messages to users requesting for text input?', 'Display()', 'Prompt()', 'Alert()', 'GetInput()', 'Prompt()'),
(35, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'HTML stands for?', 'Hyper Text Markup Language', 'High Text Markup Language', 'Hyper Tabular Markup Language', 'None of these', 'Hyper Text Markup Language'),
(36, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'The function returns a Boolean value that indicates whether a specified expression can be evaluated as a number; in ASP is', 'IsNumeric()', 'IsNumber()', 'IsNotNumeric()', 'IsNotNumber()', 'IsNumeric()'),
(37, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'HTML is a subset of', 'SGMT', 'SGML', 'SGMD', 'None of these', 'SGML'),
(38, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'Any part of the graphic that is not included in another hot zone is considered to be part of', 'Rect', 'Point', 'Default', 'Polygon', 'Default'),
(39, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'The body tag usually used after', 'Title tag', 'HEAD tag', 'EM tag', 'FORM tag', 'HEAD tag'),
(40, 'CSE', 5, 'INTERNET AND WEB TECHNOLOGY', 'Which of the following tag is used to mark a beginning of paragraph?', 'TD', 'br', 'p', 'TR', 'p');

-- --------------------------------------------------------

--
-- Table structure for table `result`
--

CREATE TABLE `result` (
  `rid` int(11) NOT NULL,
  `sid` int(11) DEFAULT NULL,
  `captureImg` varchar(225) NOT NULL,
  `subject` varchar(225) NOT NULL,
  `total_question` int(11) DEFAULT NULL,
  `total_ques_attempt` int(11) DEFAULT NULL,
  `correct_answer` int(11) DEFAULT NULL,
  `date` date DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `students`
--

CREATE TABLE `students` (
  `sid` int(11) NOT NULL,
  `name` varchar(225) DEFAULT NULL,
  `dob` varchar(10) DEFAULT NULL,
  `rollno` varchar(15) DEFAULT NULL,
  `dp` varchar(500) NOT NULL,
  `branch` varchar(50) DEFAULT NULL,
  `semester` int(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `students`
--

INSERT INTO `students` (`sid`, `name`, `dob`, `rollno`, `dp`, `branch`, `semester`) VALUES
(1, 'DIVYANSHU SHRIVASTAVA', '14-11-1999', '0821CS203D02', 'upload/pic_20220411154308.jpeg', 'CSE', 5),
(5, 'JUHI SINGH', '06-05-1999', '0821CS205D05', '', 'CSE', 5);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `contact` (`contact`);

--
-- Indexes for table `exam_schedule`
--
ALTER TABLE `exam_schedule`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `mcq`
--
ALTER TABLE `mcq`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `result`
--
ALTER TABLE `result`
  ADD PRIMARY KEY (`rid`);

--
-- Indexes for table `students`
--
ALTER TABLE `students`
  ADD PRIMARY KEY (`sid`),
  ADD UNIQUE KEY `rollno` (`rollno`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `exam_schedule`
--
ALTER TABLE `exam_schedule`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `mcq`
--
ALTER TABLE `mcq`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=72;

--
-- AUTO_INCREMENT for table `result`
--
ALTER TABLE `result`
  MODIFY `rid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;

--
-- AUTO_INCREMENT for table `students`
--
ALTER TABLE `students`
  MODIFY `sid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
